### ISSUE TITLE
Can pygenprop replace assign_genome_properties.pl ?

### ISSUE THREAD

**Issue by SilasK** [Micromeda/pygenprop#32]
If I understand your code correctly you can parse the long format output of `assign_genome_properties.pl` from the genome properties, but there is no script to infer the genome properties from the output of interposcan directly.

**Comment by LeeBergstrand** [comment]
Hi @SilasK,

**That is correct. The original plan was to simply parse the long format output from ```assign_genome_properties.pl``` and this is what the code can do currently.** 

However, I noticed that the long form file format only contained results for lower level genome properties such as **Systems** and **Pathways** but not for all types of genome properties (e.g. **Catagories**) in the tree. See the diagram below:

![genome properties types](https://user-images.githubusercontent.com/5819462/49703755-201b4a80-fbd7-11e8-83bb-9cee12ef14e7.png)

Since my visualization software uses all levels of genome properties I had to write code to do my own assignments for higher level properties.

My assignment code can be found in this file: https://github.com/Micromeda/pygenprop/blob/master/pygenprop/results.py

Specifically, the following functions:

- assign_results_to_property_and_children()
- assign_step_result()
- assign_property_result_from_required_steps()
- assign_result_from_child_assignment_results()

These functions could potentially be used to assign genome property results InterProScan output.

**Comment by LeeBergstrand** [comment]
For the functionality to work you would need to do the following. Note: this is based on my basic understanding of the Perl code in ```assign_genome_properties.pl```. I still need to reverse engineer it further to have a better understanding of it.

1. Take the ```InterProScan.tsv``` extract the column with InterPro identifiers.
2. Reduce this list of InterPro identifiers to a unique set.
3. Grab leaf genome properties and iterate through each of their steps and check if the step's evidence identifiers are in the list of InterProScan identifiers.
4. Assign steps as yes or no accordingly (filling out step assignments dict). 
5. Assign leaf level genome properties (could use existing functions above).
6. Assign higher genome properties for leaf properties.
7. Check these assignments match those from ```assign_genome_properties.pl```
8. Write some unit tests.

**Comment by LeeBergstrand** [comment]
@SilasK Prototype code is here: https://github.com/Micromeda/pygenprop/blob/assign_from_interpro_scan/prototype_assign_from_interproscan.ipynb

**Comment by LeeBergstrand** [comment]
Looks like there are some anomalies. I am investigating.

**Comment by SilasK** [comment]
Great, I will look at it. I found out that assign_genome_properties.pl uses
only the annotations (Pfam, Tigrfam,.. ) and apparently not the Interpro
ids.

**Comment by LeeBergstrand** [comment]
@SilasK https://github.com/ebi-pf-team/genome-properties/issues/30

**Comment by LeeBergstrand** [comment]
@SilasK Completed in https://github.com/Micromeda/pygenprop/pull/33

**Comment by LeeBergstrand** [comment]
Still on the develop branch. I'm going to be working on documentation.

**Comment by LeeBergstrand** [comment]
Summary can be found here.

https://github.com/Micromeda/pygenprop/blob/d284f2bb26adfab2035f2eefd1c7d7f5ada07c29/pygenprop/testing/compare_assignment_to_assign_properties_perl.ipynb

There are some difference, however, these are due to `assign_genome_properties.pl` not working correctly.
